language: java
<<<<<<< HEAD
<<<<<<< HEAD
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6
=======

jdk:
 - openjdk8
>>>>>>> 50782a3e55e703cfd19bcfb2ba384aced1aab41c
=======
jdk:
  - oraclejdk11
  - openjdk11
before_install:
  - sudo apt-get install ant-optional
>>>>>>> f7d176c9b8ec10fa94d5a1e6d564ee3a48265d91
