language: java
<<<<<<< HEAD
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7
  - openjdk6
=======

jdk:
 - openjdk8
>>>>>>> 50782a3e55e703cfd19bcfb2ba384aced1aab41c
